CREATE TABLE voters (
 id INT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(255) NOT NULL,
 birthdate DATE NOT NULL,
 address VARCHAR(255) NOT NULL,
 registered_to_vote BOOLEAN NOT NULL DEFAULT 0
);